### ISSUE TITLE
Error load model "custom_op_cliptok.onnx" saying this is an invalid model when run the program

### ISSUE THREAD

**Issue by pinkli** [cassiebreviu/StableDiffusion#9]
the stack is:
```
Unhandled exception. Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:InvalidGraph] Load model from D:\Projects\StableDiffusion\StableDiffusion\text_tokenizer\custom_op_cliptok.onnx failed:This is an invalid model. In Node, ("bpetok", CLIPTokenizer, "ai.onnx.contrib", -1) : ("string_input": tensor(string),) -> ("input_ids": tensor(int64),"attention_mask": tensor(int64),) , Error Node (bpetok) has output size 2 not in range [min=3, max=3].
   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   at Microsoft.ML.OnnxRuntime.InferenceSession.Init(String modelPath, SessionOptions options, PrePackedWeightsContainer prepackedWeightsContainer)
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath, SessionOptions options)
   at StableDiffusion.TextProcessing.TokenizeText(String text) in D:\Projects\StableDiffusion\StableDiffusion\TextProcessing.cs:line 20
   at StableDiffusion.Program.Main(String[] args) in D:\Projects\StableDiffusion\StableDiffusion\Program.cs:line 25
```
on Windows 10, dotnet SDK 7.0, on branch `direct-ML-EP`  
I built the ortextension.dll from source, as solving issue #4

**Comment by pinkli** [comment]
I can't find any resource regarding the "custom_op_cliptok.onnx" file. 
Where can I download another one, or build one, any links?

**Comment by pinkli** [comment]
here is why the error I guess:
I built the ortextensions.dll from source, where  the CLIPTokenizer model expects 3 outputs:` input_ids, attention_mask and offset_mapping`. But the `custom_op_cliptok.onnx` model in this repo, has just two outputs  `input_ids, attention_mask`
![image](https://user-images.githubusercontent.com/1488256/228822027-72a9bde8-0db6-43f4-aad0-38ae00005441.png)
, so the exeption `has output size 2 not in range [min=3, max=3]`
So the solution maybe rebuilding this onnx model using the latest code, as https://github.com/microsoft/onnxruntime-extensions/blob/main/test/test_cliptok.py
I'll try this another day.
